# Generated by Django 2.2 on 2019-08-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destination',
            new_name='Destinations',
        ),
    ]
